version: "3"
services:
  redis:
    image: redis:alpine
    expose:
      - 6379
    ports:
      - 6379:6379

  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: /app
    command: gunicorn app:app -b 0.0.0.0:8000
    env_file: .env
    depends_on:
      - redis
    volumes:
      - ./:/app/:delegated
    ports:
      - 8000:8000

  worker:
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: /app
    command: celery -A app.celery worker --loglevel=INFO
    env_file: .env
    depends_on:
      - redis
    volumes:
      - ./:/app/:delegated
